;;; green-is-the-new-black-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from green-is-the-new-black-theme.el

(register-definition-prefixes "green-is-the-new-black-theme" '("green-is-the-new-black"))

;;; End of scraped data

(provide 'green-is-the-new-black-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; green-is-the-new-black-theme-autoloads.el ends here
